name: Linters (Python)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./environment-dev.yml
          environment-name: test_env
          cache-env: true
      - name: Run all linters
        shell: pwsh
        run: |
          micromamba activate test_env
          pre-commit run --all-files --verbose --show-diff-on-failure
