name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pyturbo_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: create environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./environment-dev.yml
          environment-name: test_env
          cache-env: true
          micromamba-version: "0.23.0"
      - name: run tests
        shell: bash -l -eo pipefail {0}
        run: |
          micromamba activate test_env
          pytest ./tests/ -v -s
